<?php

namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\Country;

class CountryController extends Controller
{
    public function actionIndex()
    {
        $query = Country::find();

        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $countries = $query->orderBy('name')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index', [
            'countries' => $countries,
            'pagination' => $pagination,
        ]);
    }

    public  function  actionTest()
    {
       $aa =   Country::querySql();
       echo '<pre>';
        print_r($aa);
    }



    public  function actionT(){
        $str='eyJpdGVtcyI6Ilt7XCJidXNpbmVzc0lkXCI6XCIyOFwiLFwiZ29vZHNcIjpbe1wiY2FydElkXCI6XCI5NDkwNzdcIixcImZyb21cIjpcIntcXFwic291cmNlXFxcIjpcXFwiZWNzaG9wXFxcIixcXFwiaXNwXFxcIjpcXFwibW9iaWxlXFxcIixcXFwiYXBwa2V5XFxcIjpcXFwibXh5Y190ZXN0XFxcIixcXFwibWVtYmVyX2xldmVsXFxcIjpcXFwiMFxcXCIsXFxcInRhYl8yXFxcIjpcXFwi5LuK5pel5LiK5pawXFxcIixcXFwic291cmNlX2lkXFxcIjpcXFwiMTExNjM1OFxcXCIsXFxcImdjXFxcIjpcXFwiaGljaGFvXFxcIixcXFwiZHVyYXRpb25cXFwiOlxcXCI0MTZcXFwiLFxcXCJ0c1xcXCI6XFxcIjIwMTYtMDItMTcgMDg6MTE6MzNcXFwiLFxcXCJnc3ZcXFwiOlxcXCI1LjAuMlxcXCIsXFxcInB1c2hfdG9rZW5cXFwiOlxcXCJNSTs7ZC8vaWd3RWhnQkdDSTJURzZsV3FsUHNJVmJZWUFCZ0NnR1dDSnZQeHVmOVhKcDZhQ1pTZW5zYWdFSHI5d3JxK3BGYnRHYnc5a0VHcXpwRzJib2k5N1dEbWlMcWQ4TjhXVnRZd1VTczcvaDBcXFxcdTAwM2RcXFwiLFxcXCJndFxcXCI6XFxcIk1JIDJTXFxcIixcXFwibmV0XFxcIjpcXFwid2lmaVxcXCIsXFxcInRhYl8xXFxcIjpcXFwiaG90XFxcIixcXFwib3NcXFwiOlxcXCJhbmRyb2lkXFxcIixcXFwiZ2lcXFwiOlxcXCJlNzdjODY2ZC1jZGFkLTQ5NWUtYjBhMS1jMDM3Njk2MTUxOGVcXFwiLFxcXCJwcmljZVxcXCI6XFxcIjg5LjAwXFxcIixcXFwiYnVzaW5lc3NfaWRcXFwiOlxcXCIyOFxcXCIsXFxcImFjY2Vzc190b2tlblxcXCI6XFxcImFxX2lESlFnbkxtRko0Zk5aeXZhdzB0RGlsVzRJLWNsNmtjdlp2ODlRMEVcXFwiLFxcXCJza3VfaWRcXFwiOlxcXCI0MjM5NjE2XFxcIixcXFwiZ3ZcXFwiOlxcXCI2LjYuMC4wNFxcXCIsXFxcImdzXFxcIjpcXFwiNzIweDEyODBcXFwiLFxcXCJpcFxcXCI6XFxcIjEyNC42NS4yNDEuOTBcXFwiLFxcXCJ1aWRcXFwiOlxcXCIyODIzOTk0XFxcIixcXFwiYnJhbmRfaWRcXFwiOlxcXCIyOFxcXCIsXFxcImdmXFxcIjpcXFwiYW5kcm9pZFxcXCJ9XCIsXCJnb29kc19pZFwiOlwiOVwiLFwiZ29vZHNfaW1hZ2VcIjpcImh0dHA6Ly9teHljc2t1LnFpbml1Y2RuLmNvbS9ncm91cDUvTTAwLzlGL0I1L3dLZ0JmMVZScGJLQUtyeFJBQUltTGNOZTc2VTE0My5qcGdcIixcImdvb2RzX251bWJlclwiOlwiN1wiLFwiZ29vZHNfcHJpY2VcIjpcIjg5XCIsXCJpc19wdXJjaGFzZVwiOlwiMFwiLFwicHJvZHVjdF9pZFwiOlwiMzE0NjkwXCIsXCJzb3VyY2VfaWRcIjpcIjExMTYzNThcIn1dfV0ifQ==';
       // echo base64_decode($str);

        $str2='eyJpdGVtcyI6Ilt7XCJpdGVtX2Ftb3VudFwiOlwiNjIzXCIsXCJpdGVtX3R5cGVcIjpcImJhc2VcIixcImxpc3RzXCI6W3tcImJ1c2luZXNzSWRcIjpcIjI4XCIsXCJidXNpbmVzc05hbWVcIjpcIuS8mOWTiOS8mOWTiFwiLFwiY291bnRyeVwiOntcImNvdW50cnlfaW1nXCI6XCJcIixcImNvdW50cnlfdGl0bGVcIjpcIlwifSxcImdvb2RzXCI6W3tcImNhcnRfaWRcIjpcIjk0OTA3N1wiLFwiZnJvbVwiOlwie1xcXCJzb3VyY2VcXFwiOlxcXCJlY3Nob3BcXFwiLFxcXCJpc3BcXFwiOlxcXCJtb2JpbGVcXFwiLFxcXCJhcHBrZXlcXFwiOlxcXCJteHljX3Rlc3RcXFwiLFxcXCJtZW1iZXJfbGV2ZWxcXFwiOlxcXCIwXFxcIixcXFwidGFiXzJcXFwiOlxcXCLku4rml6XkuIrmlrBcXFwiLFxcXCJzb3VyY2VfaWRcXFwiOlxcXCIxMTE2MzU4XFxcIixcXFwiZ2NcXFwiOlxcXCJoaWNoYW9cXFwiLFxcXCJkdXJhdGlvblxcXCI6XFxcIjQxNlxcXCIsXFxcInRzXFxcIjpcXFwiMjAxNi0wMi0xNyAwODoxMTozM1xcXCIsXFxcImdzdlxcXCI6XFxcIjUuMC4yXFxcIixcXFwicHVzaF90b2tlblxcXCI6XFxcIk1JOztkLy9pZ3dFaGdCR0NJMlRHNmxXcWxQc0lWYllZQUJnQ2dHV0NKdlB4dWY5WEpwNmFDWlNlbnNhZ0VIcjl3cnErcEZidEdidzlrRUdxenBHMmJvaTk3V0RtaUxxZDhOOFdWdFl3VVNzNy9oMFxcXFx1MDAzZFxcXCIsXFxcImd0XFxcIjpcXFwiTUkgMlNcXFwiLFxcXCJuZXRcXFwiOlxcXCJ3aWZpXFxcIixcXFwidGFiXzFcXFwiOlxcXCJob3RcXFwiLFxcXCJvc1xcXCI6XFxcImFuZHJvaWRcXFwiLFxcXCJnaVxcXCI6XFxcImU3N2M4NjZkLWNkYWQtNDk1ZS1iMGExLWMwMzc2OTYxNTE4ZVxcXCIsXFxcInByaWNlXFxcIjpcXFwiODkuMDBcXFwiLFxcXCJidXNpbmVzc19pZFxcXCI6XFxcIjI4XFxcIixcXFwiYWNjZXNzX3Rva2VuXFxcIjpcXFwiYXFfaURKUWduTG1GSjRmTlp5dmF3MHREaWxXNEktY2w2a2N2WnY4OVEwRVxcXCIsXFxcInNrdV9pZFxcXCI6XFxcIjQyMzk2MTZcXFwiLFxcXCJndlxcXCI6XFxcIjYuNi4wLjA0XFxcIixcXFwiZ3NcXFwiOlxcXCI3MjB4MTI4MFxcXCIsXFxcImlwXFxcIjpcXFwiMTI0LjY1LjI0MS45MFxcXCIsXFxcInVpZFxcXCI6XFxcIjI4MjM5OTRcXFwiLFxcXCJicmFuZF9pZFxcXCI6XFxcIjI4XFxcIixcXFwiZ2ZcXFwiOlxcXCJhbmRyb2lkXFxcIn1cIixcImdvb2RzQXR0clwiOlwi6aKc6ImyOum7keiJslwiLFwiZ29vZHNfYXR0cl9pZFwiOlwiNDUyNjYyXCIsXCJnb29kc0ltYWdlXCI6XCJodHRwOi8vbXh5Y3NrdS5xaW5pdWNkbi5jb20vZ3JvdXA1L00wMC85Ri9CNS93S2dCZjFWUnBiS0FLcnhSQUFJbUxjTmU3NlUxNDMuanBnXCIsXCJnb29kc05hbWVcIjpcIkhPV++8jlLvvI5VL+S8mOWTiO+8juS8mOWTiEhPV1JV5LyY5ZOIMjAxNeaWsOasvuaXtuWwmuWPjOiCqeWMheWls+WMhVwiLFwiZ29vZHNOdW1iZXJcIjpcIjdcIixcImdvb2RzU2hvcFByaWNlXCI6XCI4OS4wMFwiLFwiZ29vZHNfc25cIjpcIjZFSDA3MDE4XCIsXCJnb29kc1NvdXJlSWRcIjpcIjExMTYzNThcIixcImdvb2RzX3N0YXR1c1wiOlwiMVwiLFwiZ29vZHNfaWRcIjpcIjgzNjU3XCIsXCJwcm9kdWN0SWRcIjpcIjMxNDY5MFwiLFwiaXNFbXB0eVwiOmZhbHNlfV0sXCJvcmRlclJlbWFya1wiOlwiXCIsXCJ0b3RhbEZhcmVcIjpcIjBcIixcInRvdGFsUHJpY2VcIjpcIjYyM1wiLFwidG90YWxUYXJpZmZcIjpcIlwiLFwidG90YWxUYXJpZmZfVGlwXCI6XCJcIixcImlzRW1wdHlcIjpmYWxzZX1dLFwiaXNFbXB0eVwiOmZhbHNlfV0iLCJhZGRyZXNzIjoie1wiYWRkcmVzc1wiOlwi5YyX5Lqs5YyX5Lqs5pyd6Ziz5Yy65Lya6ZqP5pe26ZqP5pe25b6I5aSa6YWS5bqX6YWS5bqX6YWS5bqXXCIsXCJhZGRyZXNzX2lkXCI6XCIxNTA5MTRcIixcImFkZHJlc3NkZXRhaWxcIjpcIuS8mumaj+aXtumaj+aXtuW+iOWkmumFkuW6l+mFkuW6l+mFkuW6l1wiLFwiZGlzdHJpY3RcIjpcIjUwM1wiLFwiY2l0eVwiOlwiNTJcIixcImNvbnNpZ25lZVwiOlwi5o6M5aOwXCIsXCJpZF9udW1iZXJcIjpcIlwiLFwibW9iaWxlXCI6XCIxNTIwODYzNTk4NVwiLFwicHJvdmluY2VcIjpcIjJcIixcInppcGNvZGVcIjpcIlwiLFwiaXNDdXJyZW50XCI6ZmFsc2V9Iiwib3BlcmF0aW9uIjoiMSIsImNpdHkiOiI1MiIsImRpc3RyaWN0IjoiNTAzIiwicHJvdmluY2UiOiIyIiwib3JkZXJfYW1vdW50IjoiNjIzLjAwIiwib3JkZXJfYm91bnMiOiJbXSJ9';
      //  echo base64_decode($str2);

        $sre3='eyJnb29kc19pZCI6IjIyNjMzNSIsInByb2R1Y3RfaWQiOiI1NDU1NTEiLCJvcmRlcl9pZCI6IjU5MDA1NiJ9';

        echo base64_decode($sre3);
    }
}